version: '3.8'

services:
  service_1:
    build:
      context: ./service_1
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001/ping || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3

  service_2:
    build:
      context: ./service_2
    ports:
      - "8002:8002"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8002/ping || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      service_1:
        condition: service_healthy
      service_2:
        condition: service_healthy