version: '3.8'

services:
  service_1:
    build:
      context: ./service_1
    ports:
      - "8001:8001"
  
  service_2:
    build:
      context: ./service_2
    ports:
      - "8002:8002"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service_1
      - service_2